#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jun 27 18:30:30 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.8.1.zip
